# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-03 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookrent', '0002_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('last_name',)},
        ),
    ]
