# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-03 13:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookrent', '0003_auto_20161003_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_date', models.DateField(default=datetime.date.today)),
                ('returned', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookrent.Book')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookrent.Client')),
            ],
        ),
    ]
